version: '3'

services:

  api:
    build: api
    volumes:
    - "../../api:/app"
    - "${FEATER_BUILD_DATA_PATH}:/data/build"
    - "${FEATER_PROXY_DOMAIN_DATA_PATH}:/data/proxyDomain"
    - "${FEATER_ASSET_DATA_PATH}:/data/asset"
    - "${FEATER_DOCKER_SOCKET_PATH}:/var/run/docker.sock"
    ports:
    - '${FEATER_PORT}:3000'
    depends_on:
    - mongo
    networks:
    - internal
    container_name: feater_api

  spa:
    build: spa
    volumes:
    - "../../spa:/app"
    ports:
    - '${FEATER_SPA_PORT}:4200'
    networks:
    - internal
    container_name: feater_spa

  mongo:
    image: mongo:3.6
    volumes:
    - "${FEATER_MONGO_DATA_PATH}:/data/db"
    ports:
    - '${FEATER_MONGO_PORT}:27017'
    networks:
    - internal
    container_name: feater_mongo

  nginx:
    build: nginx
    volumes:
    - "${FEATER_PROXY_DOMAIN_DATA_PATH}:/etc/nginx/conf.d/proxyDomain"
    ports:
    - '${FEATER_NGINX_PORT}:80'
    networks:
    - internal
    - proxy
    container_name: feater_nginx

networks:
  internal:
  proxy:
