version: '2'

services:

  api:
    build: api
    volumes:
      - ../../../api:/app
      - ${FEAT_DATA_PATH}/repository:/data/repository
      - ${FEAT_DATA_PATH}/build:/data/build
      - ${FEAT_DATA_PATH}/proxyDomain:/data/proxyDomain
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '${FEAT_API_PORT}:3000'
    networks:
      - internal
    container_name: feat_api

  spa:
    build: spa
    volumes:
      - ../../../spa:/app
    ports:
      - '${FEAT_SPA_PORT}:4200'
    networks:
      - internal
    container_name: feat_spa

  mongo:
    image: mongo:3.6
    ports:
      - '${FEAT_MONGO_PORT}:27017'
    networks:
      - internal
    container_name: feat_mongo

  nginx:
    build: nginx
    volumes:
      - ${FEAT_DATA_PATH}/proxyDomain:/etc/nginx/conf.d/proxyDomain
    ports:
      - '${FEAT_NGINX_PORT}:80'
    networks:
      - internal
      - build
    container_name: feat_nginx

  elasticsearch:
    build:
      context: ./elasticsearch
    ports:
      - '${ELASTICSEARCH_PORT}:9200'
    networks:
      - internal
    container_name: feat_elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - '${KIBANA_PORT}:5601'
    networks:
      - internal
    container_name: feat_kibana

networks:
  internal:
  build:
